import networkx as nx
import random
import community as community_louvain

def louvain_partition(G):
    partition = community_louvain.best_partition(G)

    # convert dict → list of communities
    # py louvain returns a dict. node => comm ID
    # this is converted into a list of node lists
    # so it matches the format modularity() expects
    communities = {}
    for node, comm_id in partition.items():
        communities.setdefault(comm_id, []).append(node)

    return list(communities.values())

# load graph from edgelist file
# aimed for graphs generated by generate.py
# but should work for any file of the form
# nodeA nodeB
def load_network(filename):
	G = nx.Graph()

	with open(filename, "r") as f:
		for line in f:
			line = line.strip()

			if line.startswith("#") or not line:
				continue

			i, j=map(int, line.split())
			G.add_edge(i,j)
	return G

# baseline partition
# nodes are assigned randomly to equal size
# comms for louvain comparison

def random_partition(G, k, seed=None):
	if seed is not None:
		random.seed(seed)

	nodes = list(G.nodes())
	random.shuffle(nodes)		# shuffle node order for random comm assignment

	communities = [[] for _ in range(k)]	# empty comm initialisation

	# communities are distributed as evenly as possible
	# to isolate the effect of community count

	for i, node in enumerate(nodes):
		communities[i % k].append(node)

	return communities

# compute modularity from the formula:
# Q = (1/2m)*SUM[A_ij - (k_i k_j / 2m)]delta(ci,cj)
# any inefficiency resulting from this implementation is intentional
# as i was trying to internalise this exact formula specifically
def modularity(G, communities):
	m = G.number_of_edges()			# total edge count
	if m == 0:
		return 0.0
	deg = dict(G.degree())			# degree of every node

	# build a lookup table so each node's comm can be found
	node_to_comm = {}
	for ci, comm in enumerate(communities):
		for n in comm:
			node_to_comm[n]=ci

	Q = 0.0
	nodes = list(G.nodes())

	for i in nodes:									# inefficient but i want to
		for j in nodes:								# adapt the formula faithfully

			delta = 1 if node_to_comm[i] == node_to_comm[j] else 0	# delta(c_i,c_j)
			if not delta:											# 1 if nodes are
				continue											# in the same comm
																	# otherwise 0

			Aij = 1 if G.has_edge(i,j) else 0		#A_ij. 1 if ij share an edge

			expected = (deg[i]*deg[j])/(2*m)		#(k_i k_j)/2m, expected P(edge) for
													#a degree preserving random graph
			Q += (Aij - expected)	# accumulate pair's contribution to tot.modularity

	return Q / (2*m) #normalise Q over 2m as seen in the OG equation

#def Q_for_k(G, k, trials=100):					# Older version
#	Q_values=[]									#
#	for t in range(trials):						# Deprecated after
#		communities = random_partition(G, k)	# Louvain modularity
#		Q=modularity(G, communities)			# was implemented
#		Q_values.append(Q)						#
#		return sum(Q_values)/trials				# Retained for reference
		
###############################
#	vestigial test block	  #
#	to run modularity.py	  #
###############################
if __name__ == "__main__":
    G = load_network("network.edgelist")

    communities = louvain_partition(G)
    Q = modularity(G, communities)

    print("n =", G.number_of_nodes())
    print("m =", G.number_of_edges())
    print("communities =", len(communities))
    print("Q =", Q)